version: "3.8"
services:
    mongo:
        image : mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - /Users/martas/Work/Docker/mongoDB:/data/db
        ports:
            - 27020:27017

    web:
        image: nginx
        volumes:
            - ./nginx/templates:/etc/nginx/templates
        ports:
            - "8079:80"
        environment:
            - NGINX_HOST=tjv.moje
            - NGINX_PORT=80

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 1889:1883
        volumes:
            - ./rabbitmq/config:/etc/rabbitmq/
            - ./rabbitmq/data/rabbitmq/data/:/var/lib/rabbitmq/

    platform:
        build: ../
        volumes:
            - ./rabbitmq/config:/etc/rabbitmq/
            - ./rabbitmq/data/rabbitmq/data/:/var/lib/rabbitmq/
        environment: 
            - HOME_PAGE=https://dev.iotplatforma.cloud
            - FIREBASE_ADMIN_PATH=/keys/firebase.json
            - DATABASE_USERNAME=root
            - DATABASE_PASSWORD=root
            - DATABASE_NAME=IOTPlatform_v3
            - DATABASE_URL=mongo
            - DATABASE_PORT=27017
            - PORT=8080
            - AUTH_PORT=8081
            - MQTT_PORT=1883
            - MQTT_URL=mqtt://rabbitmq
            - MQTT_USERNAME=mqttUser
            - MQTT_PASSWORD=42ds4298ds
            - AGENDA_JOB_TYPES=email
            - AGENDA_DB_NAME=agenda-test-iot_v3
            - NODE_ENV=production
            - JWT_PUBLIC_KEY=/keys/platform/jwtRS256.key.pub
            - JWT_PRIVATE_KEY=/keys/platform/jwtRS256.key
            - EMAIL_HOST=
            - EMAIL_USERNAME=
            - EMAIL_PASSWORD=
